<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Chamando função Lambda com Detalhes do Erro</title>
</head>
<body>
  <h1>Chamando função Lambda</h1>
  <p>Clique no botão para chamar a função Lambda:</p>
  <button id="btn-lambda">Chamar Lambda</button>

  <script>
    const btnLambda = document.getElementById('btn-lambda');
    let response = "nada";
  
    btnLambda.addEventListener('click', async () => {
      try {
        // Chamada à API Lambda
        response = await fetch('https://tssvso6yoq3rw6bhppn63agnae0dbsqw.lambda-url.us-east-2.on.aws/', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({"id": "1cnB0IVc7v7j3WTKiSV0IjQOdXQBK97J4iS5-g2DCwD4"}),
        });
  
        // Processar a resposta JSON
        const result = await response;
  
        // Exibir o resultado no console
        console.log(result.username); // Acesse a propriedade 'username' da resposta
      } catch (error) {
        console.error('Erro durante a chamada assíncrona:', error);
      }
    });
  </script>
  
</body>
</html>
